---
title: "Week 13 Class A"
author: "SZR"
format: html
---


### Iterative Coding and Intro to Models

#Load Libraries
```{r}
#| message: false

library(tidyverse)
library(here)
```


## Learning how to loop
```{r}
#| message: false

print(paste("The year is", 2000))
years <- c(2015:2021)
for (i in years) { # set up the for loop where I is the index
  print(paste("The year is", i))
}

year_data<-tibble(year =  rep(NA, length(years)),  # column name for year
                   year_name = rep(NA, length(years))) # column name for the year name

for (i in 1:length(years)){ # set up the for loop where i is the index
  year_data$year_name[i]<-paste("The year is", years[i]) # loop over year name
  year_data$year[i]<-years[i] # loop over year
}
```


#Looping reading in data
```{r}
#| message: false

testdata<-read_csv(here("Week_13", "Data","011521_CT316_1pcal.csv"))

CondPath<-here("Week_13", "Data", "cond_data")
files <- dir(path = CondPath,pattern = ".csv")

cond_data<-tibble(filename =  rep(NA, length(files)),  # column name for year
                   mean_temp = rep(NA, length(files)), # column name for the mean temperature
                   mean_sal = rep(NA, length(files)) # column name for the mean salinity
                   ) # column name for the year name

raw_data<-read_csv(paste0(CondPath,"/",files[1])) # test by reading in the first file and see if it works
mean_temp<-mean(raw_data$Temperature, na.rm = TRUE) # calculate a mean

for (i in 1:length(files)){ # loop over 1:3 the number of files 
raw_data<-read_csv(paste0(CondPath,"/",files[i])) #glimpse(raw_data)
cond_data$filename[i]<-files[i]
cond_data$mean_temp[i]<-mean(raw_data$Temperature, na.rm =TRUE)
cond_data$mean_sal[i]<-mean(raw_data$Salinity, na.rm =TRUE)
} 

cond_data

```


## Using purrr
#Simple example
```{r}
#| message: false

1:10 # a vector from 1 to 10 (we are going to do this 10 times)

1:10 %>% # a vector from 1 to 10 (we are going to do this 10 times) %>% # the vector to iterate over
  map(rnorm, n = 15)  %>% # calculate 15 random numbers based on a normal distribution in a list 
  map_dbl(mean) # calculate the mean. It is now a vector which is type "double"
```


#More complex example using cond_data
```{r}
#| message: false

files <- dir(path = CondPath,pattern = ".csv", full.names = TRUE)
#save the entire path name
data<-files %>%
  set_names()%>% # set's the id of each list to the file name
  map_df(read_csv,.id = "filename") %>% # map everything to a dataframe and put the id in a column called filename
  group_by(filename) %>%
  summarise(mean_temp = mean(Temperature, na.rm = TRUE),
            mean_sal = mean(Salinity,na.rm = TRUE))
```
