---
title: "Week_13_ClassB"
author: "SZR"
format: html
---

### Basic Modeling

# Load Libraries
```{r}
#| message: false

library(tidyverse)
library(here)
library(palmerpenguins)
library(broom)
library(performance) 
library(modelsummary)
library(tidymodels)
library(pandoc)
library(wesanderson)
```


```{r}
#| message: false

Peng_mod<-lm(bill_length_mm ~ bill_depth_mm*species, data = penguins)
check_model(Peng_mod)
anova(Peng_mod)
summary(Peng_mod) ## gives the effect size
coeffs<-tidy(Peng_mod) # viewing with broom (just put tidy() around it)
coeffs
resid_fitted<-augment(Peng_mod)
resid_fitted

# New model
Peng_mod_noX<-lm(bill_length_mm ~ bill_depth_mm, data = penguins)
#Make a list of models and name them
models<-list("Model with interaction" = Peng_mod,
             "Model with no interaction" = Peng_mod_noX)
#Save the results as a .docx
modelsummary(models, output = here("Week_13","output","table.docx"))

modelplot(models) +
    labs(x = 'Coefficients', 
         y = 'Term names') +
    scale_color_manual(values = wes_palette('Darjeeling1'))

models<- penguins %>%
  ungroup()%>% # the penguin data are grouped so we need to ungroup them
    nest(.by = species) %>% # nest all the data by species
    mutate(fit = map(data, ~lm(bill_length_mm~body_mass_g, data = .)))
models$fit

results<-models %>%
   mutate(coeffs = map(fit, tidy), # look at the coefficients
          modelresults = map(fit, glance)) %>% # R2 and others
  select(species, coeffs, modelresults) %>% # only keep the results
   unnest() # put it back in a dataframe and specify which columns to unnest
results
```

