---
title: "Week 13 HW"
author: "SZR"
format: html
---

### Iterative Coding

## Load Libraries
```{r}
#| message: false

library(tidyverse)
library(here)
```


## Reading in Data with a loop
```{r}
#| message: false

HW <- here("Week_13", "Data", "homework", "TP1.csv") ## testing the file path 

hw_data <- here("Week_13", "Data", "homework") ## sets the file path
files <- dir(path = hw_data, pattern = ".csv") ## uses set file path to retrieve any .csv files

tp_data <- tibble(
  filename = rep(NA_character_, length(files)),
  mean_temp = rep(NA_real_, length(files)),
  sd_temp = rep(NA_real_, length(files)),
  mean_light = rep(NA_real_, length(files)),
  sd_light = rep(NA_real_, length(files))
)
```


## Data Processing
Calculate the mean and standard deviation for Temp.C and Intensity.lux 
```{r}
#| message: false

## turning this into a loop for TP1, TP2, TP3, TP4

for (i in 1:length(files)){ ## setting the loop for all files
raw_tp <- read_csv(paste0(hw_data, "/", files[i]))
tp_data$filename[i] <- files[i]
  tp_data$mean_temp[i] <- mean(raw_tp$Temp.C, na.rm = TRUE)
  tp_data$sd_temp[i] <- sd(  raw_tp$Temp.C, na.rm = TRUE)
  tp_data$mean_light[i] <- mean(raw_tp$Intensity.lux, na.rm = TRUE)
  tp_data$sd_light[i] <- sd(  raw_tp$Intensity.lux, na.rm = TRUE)
}

print(tp_data)
```

Doing the same thing with the map() function
```{r}
#| message: false

tp_data_map <- dir(path = hw_data, pattern = ".csv", full.names = TRUE) %>%
  set_names() %>%
  map_df(read_csv, .id = "filename") %>%
  group_by(filename) %>%
  summarise(
    mean_temp = mean(Temp.C, na.rm = TRUE),
    sd_temp = sd(  Temp.C, na.rm = TRUE),
    mean_light = mean(Intensity.lux, na.rm = TRUE),
    sd_light = sd(  Intensity.lux, na.rm = TRUE)
  )

tp_data_map
```

