---
title: "Week 9 HW"
author: "SZR"
format: html
---

Loading libraries
```{r}
#| message: false

library(here)
library(janitor)
library(dplyr)
library(tidyverse)
library(forcats)
library(ggplot2)
```

Reading data
```{r}
#| message: false

intertidal <- read_csv(here("Week_09", "Data", "intertidaldata.csv"))
intertidal_lat <- read_csv(here("Week_09", "Data", "intertidaldata_latitude.csv"))
```

Data processing
```{r}
#| message: false

intertidal <- intertidal %>%
  rename(
    algae_count = Algae,
    mussel_count= Mussels,
    small_barnacle_count = `Small Barnacles`,
    large_barnacle_count = `Large Barnacles`,
    gooseneck_barnacle_count = `Gooseneck Barnacles`,
    anemone_count = Anemone,
    whelk_count = `Whelks (Counts)`,
    crab_count = `Crabs (Counts)`,
    star_count = `Stars (Counts)`
  ) %>%
  mutate(across(matches("count"), ~ifelse(.x == 0, NA, .x))) 

intertidal_summary <- intertidal %>%
  group_by(Site) %>%
  summarise(across(where(is.numeric), sum, na.rm= TRUE)) %>%
  left_join(intertidal_lat, by = "Site") %>%
  clean_names() %>%
  mutate(site = fct_reorder(site, latitude)) %>%
  arrange(desc(latitude))
```

```{r}
intertidal_summary %>% 
  ggplot(aes(x = fct_reorder(site, latitude), ## order the site based on latitude
             y = gooseneck_barnacle_count)) +
  geom_col() +
  labs(x = "Site",
       y = "Gooseneck Barnacle Count",
       title = "Gooseneck Barnacle Count per Location") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) ## adjusting site labels

ggsave(
  here("Week_09", "Outputs", "Gooseneck_barnacle_plot.png"),
  width = 8,
  height = 5,
  dpi = 300
)
```

