---
title: "Week 07 Class"
author: "SZR"
format: html
---


# Load **Libraries**
```{r}
library(maps)
library(mapproj)
library(mapdata)
library(tidyverse)
library(here)
```

# Loading **data**
```{r}
popdata<- read_csv(here("Week_07", "Data", "CApopdata.csv"))
stars <- read_csv(here("Week_07", "Data", "stars.csv"))
```

# **Data analysis**
## making vectors for specific data regions
```{r}
world <- map_data("world")
usa <- map_data("usa")
italy <- map_data("italy")
state <- map_data("state")
counties <- map_data("county")
```

# Making a **map of the world**
```{r}
ggplot()+
  geom_polygon(data = world, 
               aes(x = long, y = lat, group = group,
                   fill = region),
               color = "black") +
  theme_minimal()+
  guides(fill = FALSE)+
  theme(panel.background = element_rect(fill = "lightblue")) +
  coord_map(projection = "sinusoidal",
           xlim = c(-180,180))
```
# Looking at **States Data**
```{r}
CA_data <-state %>%
  filter(region == "california")

ggplot()+
  geom_polygon(data = CA_data, 
               aes(x = long, y = lat, group = group,
                   fill = region),
               fill = "black") +
  theme_minimal()+
  guides(fill = FALSE)+
  theme(panel.background = element_rect(fill = "lightblue")) 
```
# Making a **region specific plot**
```{r}
CApop_county <- popdata %>%
  select("subregion" = County, Population) %>% ## changing counto to "subregion" to maintain consistency betwn data sets
  inner_join(counties) %>%
  filter(region == "california") ## only looking at cali data

ggplot()+
  geom_polygon(data = CApop_county,
               aes(x = long,
                   y = lat,
                   group = group,
                   fill = Population),
               color = "black")+
  geom_point(data = stars,
             aes(x = long,
                 y = lat,
                 size = star_no))+
  coord_map()+
  theme_void()+
  scale_fill_gradient(trans = "log10") + ## log transforming the population
  labs(size = "# stars/m2")

ggsave(here("Week_07", "output", "CApop.pdf"))
```


